# nodes: node-a-2core, node-b-4core, node-c-8core
apiVersion: v1
kind: Pod
metadata:
  name: some-memcached
  labels:
    name: some-memcached
spec:
  containers:
    - image: anakli/memcached:t1
      name: memcached
      imagePullPolicy: Always
      command: ["/bin/sh"]
      #args: ["-c", "taskset -c 0 ./memcached -t 1 -u memcache"]
      args: ["-c", "./memcached -t 1 -u memcache"]
      resources:
            limits:
              cpu: "1"
  nodeSelector:
    cca-project-nodetype: "node-c-8core"